import { cellToParent } from "h3-js"

import { LandH3Cell } from "../data/coverage_land/uk/data"
import { SUBURBAN_DEMAND_MULTIPLIER, URBAN_DEMAND_MULTIPLIER } from "../data/power_demand/relative_demand"
import { uk_demand_gw_by_hour_2018 } from "../data/power_demand/uk"
import { promise_aggregated_power_plants_by_h3_cell } from "../data/power_plants"
import type { AggregatedPowerPlantData } from "../data/power_plants/interface"
import { AllCapacityFactorData, promise_load_all_capacity_factor_data } from "../data/wind_and_solar_capacity/load_data"
import pub_sub from "../state/pub_sub"
import { get_capacity_factor_mix } from "../utils/capacity_factor_data"
import { DemandByH3R4Cell, DemandForCell } from "./interface"
import { SupplyGWByType } from "./old_interface"


const promise_capacity_factor_data = promise_load_all_capacity_factor_data()

// At each moment, the model wants to calculate:
// * how much energy was generated by each type of source by each cell since the
//   last timestep
//     * how much electricity is being generated by each aggregated cell of wind
//       and solar power plants.
// * how much electricity is being consumed by the demand in each aggregated cell
//
// This then enables:
// * each cell to show an indicator when X energy has been generated by a source
//     e.g. there might be wind, gas, nuclear, solar, and battery storage in one
//          cell and these will generate different amounts of electricity at
//          different times.
// * also enables the model to calculate a redimentary electricity grid supply/demand
//   balance for each cell.
// * this enables showing cells which are lacking power supply
// * and showing cells which are generating excess power supply and being
//   curtailed
// * when the marginal electricity pricing is modelled we can also show which
//   cells are costing money because NESO asks it to reverse its bid.


type GenerationBySource = { generated_mw: number; capacity_mw: number }
interface GenerationByCell
{
    h3_id: string
    wind: GenerationBySource
    solar: GenerationBySource
    gas: GenerationBySource
    nuclear: GenerationBySource
    battery: GenerationBySource
    hydro_pumped_storage: GenerationBySource
    total_generated_mw: number
    total_capacity_mw: number
}


/**
 * Compute instantaneous generation (MW) for each aggregated H3 cell.
 * datetime indices should be the integer indices used by the capacity factor data.
 * A mix between two adjacent datetime indices can be provided to interpolate.
 */
function get_generation_by_h3_cell(
    capacity_factor_data: AllCapacityFactorData,
    aggregated_power_plants_by_h3_cell: Record<string, AggregatedPowerPlantData>,
    datetime_index1: number,
    datetime_index2: number,
    mix: number
): Record<string, GenerationByCell>
{
    const wind_cf = capacity_factor_data.wind
    const solar_cf = capacity_factor_data.solar

    const out: Record<string, GenerationByCell> = {}

    for (const [h3_id, data] of Object.entries(aggregated_power_plants_by_h3_cell))
    {
        const wind_capacity_mw = data.wind_farm.capacity_mw ?? 0
        const solar_capacity_mw = data.solar_farm.capacity_mw ?? 0
        const gas_capacity_mw = data.gas_plant.capacity_mw ?? 0
        const nuclear_capacity_mw = data.nuclear_plant.capacity_mw ?? 0

        const cf_wind = get_capacity_factor_mix(wind_cf, datetime_index1, datetime_index2, mix, h3_id) ?? 0
        const cf_solar = get_capacity_factor_mix(solar_cf, datetime_index1, datetime_index2, mix, h3_id) ?? 0

        const wind_generated_mw = wind_capacity_mw * cf_wind
        const solar_generated_mw = solar_capacity_mw * cf_solar
        const gas_generated_mw = 0 // TODO: get from data
        const nuclear_generated_mw = 0 // TODO: get from data
        const battery_generated_mw = 0 // TODO: get from data
        const hydro_pumped_storage_generated_mw = 0 // TODO: get from data

        const total_generated_mw = wind_generated_mw + solar_generated_mw + gas_generated_mw + nuclear_generated_mw + battery_generated_mw + hydro_pumped_storage_generated_mw
        const total_capacity_mw = wind_capacity_mw + solar_capacity_mw + gas_capacity_mw + nuclear_capacity_mw

        out[h3_id] = {
            h3_id,
            wind: { generated_mw: wind_generated_mw, capacity_mw: wind_capacity_mw },
            solar: { generated_mw: solar_generated_mw, capacity_mw: solar_capacity_mw },
            gas: { generated_mw: gas_generated_mw, capacity_mw: gas_capacity_mw },
            nuclear: { generated_mw: nuclear_generated_mw, capacity_mw: nuclear_capacity_mw },
            battery: { generated_mw: battery_generated_mw, capacity_mw: 0 },
            hydro_pumped_storage: { generated_mw: hydro_pumped_storage_generated_mw, capacity_mw: 0 },
            total_generated_mw,
            total_capacity_mw,
        }
    }

    return out
}



function get_initial_demand_by_h3_cell(h3_land_cells: LandH3Cell[]): DemandByH3R4Cell
{
    const demand_by_h3r4: DemandByH3R4Cell = {}
    let total_h5_cells = 0

    h3_land_cells.forEach(cell =>
    {
        if (cell.type !== "suburban" && cell.type !== "urban") return
        total_h5_cells++
        const h3_res5_id = cell.id
        const h3_res4_id = cellToParent(h3_res5_id, 4)

        const entry: DemandForCell = demand_by_h3r4[h3_res4_id] || {
            h3r4_id: h3_res4_id,
            proportional_demand: 0,
            demand_gw: 0,
        }

        entry.proportional_demand += cell.type === "suburban" ? SUBURBAN_DEMAND_MULTIPLIER : URBAN_DEMAND_MULTIPLIER
        demand_by_h3r4[h3_res4_id] = entry
    })

    Object.values(demand_by_h3r4).forEach(entry =>
    {
        entry.proportional_demand /= total_h5_cells
    })

    return demand_by_h3r4
}


function mutate_demand_by_h3_cell(time_size: number, demand_by_h3r4: Record<string, DemandForCell>, datetime_index1: number, datetime_index2: number, mix: number): number
{
    // const year_demand = daily_profiles["2024"]
    // const summer_day_demand = year_demand.low_demand.data
    // const winter_day_demand = year_demand.high_demand.data
    // // Take the datetime_index1 and assume it is hours per year of 8760, the
    // // calculate how much of the summer or winter day profile to use.  This is a
    // // simplification
    // const annual_mix

    const demand_gw1 = uk_demand_gw_by_hour_2018[datetime_index1 % time_size] ?? 0
    const demand_gw2 = uk_demand_gw_by_hour_2018[datetime_index2 % time_size] ?? 0
    const demand_gw = demand_gw1 * (1 - mix) + demand_gw2 * mix

    Object.values(demand_by_h3r4).forEach(entry =>
    {
        entry.demand_gw = entry.proportional_demand * demand_gw
    })

    return demand_gw
}


const last_updated_at =
{
    datetime_index1: null as number | null,
    real_time: 0,
}
const max_update_frequency_ms = 1000
export function init_model_power_supply_updates(h3_land_cells: LandH3Cell[])
{
    const demand_by_h3r4 = get_initial_demand_by_h3_cell(h3_land_cells)

    const unsub = pub_sub.sub("simulation_datetime", (payload) =>
    {
        const current_time = performance.now()
        if (last_updated_at.datetime_index1 === payload.datetime_annual_hourly_index1 && current_time - last_updated_at.real_time < max_update_frequency_ms)
        {
            // Don't update more than max_update_frequency_ms for the same datetime index
            return
        }
        last_updated_at.datetime_index1 = payload.datetime_annual_hourly_index1
        last_updated_at.real_time = current_time

        console.log("Updating model power supply for datetime index", payload.datetime_annual_hourly_index1)

        ;(async () =>
        {
            try
            {
                const capacity_factor_data = await promise_capacity_factor_data
                const aggregated_power_plants_by_h3_cell = await promise_aggregated_power_plants_by_h3_cell as Record<string, AggregatedPowerPlantData>
                const by_cell = get_generation_by_h3_cell(
                    capacity_factor_data,
                    aggregated_power_plants_by_h3_cell,
                    payload.datetime_annual_hourly_index1,
                    payload.datetime_annual_hourly_index2,
                    payload.datetime_annual_hourly_index_mix,
                )
                const supply_gw_by_type: SupplyGWByType = {
                    wind: 0,
                    solar: 0,
                    gas: 0,
                    nuclear: 0,
                    battery: 0,
                    hydro_pumped_storage: 0,
                }
                const capacity_gw_by_type: SupplyGWByType = {
                    wind: 0,
                    solar: 0,
                    gas: 0,
                    nuclear: 0,
                    battery: 0,
                    hydro_pumped_storage: 0,
                }

                let total_mw = 0
                Object.values(by_cell).forEach(c =>
                {
                    total_mw += c.total_generated_mw
                    supply_gw_by_type.wind += c.wind.generated_mw / 1000
                    supply_gw_by_type.solar += c.solar.generated_mw / 1000
                    supply_gw_by_type.gas += c.gas.generated_mw / 1000
                    supply_gw_by_type.nuclear += c.nuclear.generated_mw / 1000
                    supply_gw_by_type.battery += c.battery.generated_mw / 1000
                    supply_gw_by_type.hydro_pumped_storage += c.hydro_pumped_storage.generated_mw / 1000

                    capacity_gw_by_type.wind += c.wind.capacity_mw / 1000
                    capacity_gw_by_type.solar += c.solar.capacity_mw / 1000
                    capacity_gw_by_type.gas += c.gas.capacity_mw / 1000
                    capacity_gw_by_type.nuclear += c.nuclear.capacity_mw / 1000
                    capacity_gw_by_type.battery += c.battery.capacity_mw / 1000
                    capacity_gw_by_type.hydro_pumped_storage += c.hydro_pumped_storage.capacity_mw / 1000
                })

                const supply_gw = total_mw / 1000

                const demand_gw = mutate_demand_by_h3_cell(
                    capacity_factor_data.wind.date_time_to_index.size,
                    demand_by_h3r4,
                    payload.datetime_annual_hourly_index1,
                    payload.datetime_annual_hourly_index2,
                    payload.datetime_annual_hourly_index_mix
                )

                pub_sub.pub("power_supply_and_demand", {
                    supply_gw,
                    supply_gw_by_type,
                    capacity_gw_by_type,
                    generation_by_cell: by_cell,
                    demand_gw,
                    demand_by_h3r4,
                    datetime_ms: payload.datetime_ms,
                })
            }
            catch (e)
            {
                // Don't throw — log and continue
                // eslint-disable-next-line no-console
                console.error("Error computing generation on simulation_datetime:", e)
            }
        })()
    })

    return unsub
}
