import { cellToParent } from "h3-js"

import { deep_freeze } from "core/utils/deep_freeze"

import { DEFAULT_SPEED } from "../../state/game_datetime/constants"
import { await_aggregated_by_h3r4, hacky_get_state } from "../../state/store"
import { LandH3Cell } from "../data/coverage_land/uk/data"
import { SUBURBAN_DEMAND_MULTIPLIER, URBAN_DEMAND_MULTIPLIER } from "../data/power_demand/relative_demand"
import { uk_demand_gw_by_hour_2018 } from "../data/power_demand/uk"
import type { AggregatedPowerPlantData } from "../data/power_plants/interface"
import { AllCapacityFactorData, promise_load_all_capacity_factor_data } from "../data/wind_and_solar_capacity/load_data"
import pub_sub from "../state/pub_sub"
import { get_speed_factor, timestamp_to_index } from "../state/sim_clock"
import { get_capacity_factor_mix } from "../utils/capacity_factor_data"
import { DemandByH3R4Cell, DemandGWForH3R4, MWGenCapStoreForH3R4, ValueByPowerType, ValueByStorageType } from "./interface"


const promise_capacity_factor_data = promise_load_all_capacity_factor_data()

// At each moment, the model wants to calculate:
// * how much energy was generated by each type of source by each cell since the
//   last timestep
//     * how much electricity is being generated by each aggregated cell of wind
//       and solar power plants.
// * how much electricity is being consumed by the demand in each aggregated cell
//
// This then enables:
// * each cell to show an indicator when X energy has been generated by a source
//     e.g. there might be wind, gas, nuclear, solar, and battery storage in one
//          cell and these will generate different amounts of electricity at
//          different times.
// * also enables the model to calculate a redimentary electricity grid supply/demand
//   balance for each cell.
// * this enables showing cells which are lacking power supply
// * and showing cells which are generating excess power supply and being
//   curtailed
// * when the marginal electricity pricing is modelled we can also show which
//   cells are costing money because NESO asks it to reverse its bid.


/**
 * Compute instantaneous generation, capacity and storage (MW) for each aggregated H3 cell.
 * datetime indices should be the integer indices used by the capacity factor data.
 * A mix between two adjacent datetime indices can be provided to interpolate.
 */
function get_gen_cap_store_MW_by_h3r4_cell(
    capacity_factor_data: AllCapacityFactorData,
    aggregated_power_plants_by_h3r4_cell: Record<string, AggregatedPowerPlantData>,
    datetime_index1: number,
    datetime_index2: number,
    mix: number
): Record<string, MWGenCapStoreForH3R4>
{
    const wind_cf = capacity_factor_data.wind
    const solar_cf = capacity_factor_data.solar

    const out: Record<string, MWGenCapStoreForH3R4> = {}

    for (const [h3_id, data] of Object.entries(aggregated_power_plants_by_h3r4_cell))
    {
        const wind_capacity_MW = data.wind.capacity_MW ?? 0
        const solar_capacity_MW = data.solar.capacity_MW ?? 0
        const gas_capacity_MW = data.gas.capacity_MW ?? 0
        const hydro_river_capacity_MW = data.hydro_river.capacity_MW ?? 0
        const nuclear_capacity_MW = data.nuclear.capacity_MW ?? 0
        const battery_capacity_MW = data.battery.capacity_MW ?? 0
        const hydro_pumped_storage_capacity_MW = data.hydro_pumped_storage.capacity_MW ?? 0

        const cf_wind = get_capacity_factor_mix(wind_cf, datetime_index1, datetime_index2, mix, h3_id) ?? 0
        const cf_solar = get_capacity_factor_mix(solar_cf, datetime_index1, datetime_index2, mix, h3_id) ?? 0

        const wind_generated_MW = wind_capacity_MW * cf_wind
        const solar_generated_MW = solar_capacity_MW * cf_solar
        const nuclear_generated_MW = nuclear_capacity_MW * 0.75 // TODO: get data for this capacity factor value
        const hydro_river_generated_MW = hydro_river_capacity_MW * 0.5 // TODO: get data for this capacity factor value
        const gas_generated_MW = 0 // TODO: get from data
        const battery_generated_MW = 0 // TODO: get from data
        const hydro_pumped_storage_generated_MW = 0 // TODO: get from data

        const total_generated_MW = (
            wind_generated_MW
            + solar_generated_MW
            + gas_generated_MW
            + nuclear_generated_MW
            + hydro_river_generated_MW
            + battery_generated_MW
            + hydro_pumped_storage_generated_MW
        )
        const total_capacity_MW = (
            wind_capacity_MW
            + solar_capacity_MW
            + gas_capacity_MW
            + nuclear_capacity_MW
            + hydro_river_capacity_MW
            + battery_capacity_MW
            + hydro_pumped_storage_capacity_MW
        )

        out[h3_id] = {
            h3r4_id: h3_id,
            wind: { generated_MW: wind_generated_MW, capacity_MW: wind_capacity_MW },
            solar: { generated_MW: solar_generated_MW, capacity_MW: solar_capacity_MW },
            gas: { generated_MW: gas_generated_MW, capacity_MW: gas_capacity_MW },
            nuclear: { generated_MW: nuclear_generated_MW, capacity_MW: nuclear_capacity_MW },
            hydro_river: { generated_MW: hydro_river_generated_MW, capacity_MW: hydro_river_capacity_MW },
            battery: { generated_MW: battery_generated_MW, capacity_MW: battery_capacity_MW },
            hydro_pumped_storage: { generated_MW: hydro_pumped_storage_generated_MW, capacity_MW: hydro_pumped_storage_capacity_MW },
            total_generated_MW,
            total_capacity_MW,
        }
    }

    return out
}



function get_initial_proportional_demand_by_h3r4_cell(h3r5_land_cells: LandH3Cell[]): DemandByH3R4Cell
{
    const demand_by_h3r4: DemandByH3R4Cell = {}
    let total_h5_cells = 0

    h3r5_land_cells.forEach(cell =>
    {
        if (cell.type !== "suburban" && cell.type !== "urban") return
        total_h5_cells++
        const h3_res5_id = cell.h3h5_id
        const h3r4_id = cellToParent(h3_res5_id, 4)

        const entry: DemandGWForH3R4 = demand_by_h3r4[h3r4_id] || {
            h3r4_id,
            proportional_demand: 0,
            demand_GW: 0,
        }

        entry.proportional_demand += cell.type === "suburban" ? SUBURBAN_DEMAND_MULTIPLIER : URBAN_DEMAND_MULTIPLIER
        demand_by_h3r4[h3r4_id] = entry
    })

    Object.values(demand_by_h3r4).forEach(entry =>
    {
        entry.proportional_demand /= total_h5_cells
    })

    return demand_by_h3r4
}


function mutate_demand_by_h3_cell(time_size: number, demand_by_h3r4: Record<string, DemandGWForH3R4>, datetime_index1: number, datetime_index2: number, mix: number): number
{
    // const year_demand = daily_profiles["2024"]
    // const summer_day_demand = year_demand.low_demand.data
    // const winter_day_demand = year_demand.high_demand.data
    // // Take the datetime_index1 and assume it is hours per year of 8760, the
    // // calculate how much of the summer or winter day profile to use.  This is a
    // // simplification
    // const annual_mix

    const demand_gw1 = uk_demand_gw_by_hour_2018[datetime_index1 % time_size] ?? 0
    const demand_gw2 = uk_demand_gw_by_hour_2018[datetime_index2 % time_size] ?? 0
    const demand_gw = demand_gw1 * (1 - mix) + demand_gw2 * mix

    Object.values(demand_by_h3r4).forEach(entry =>
    {
        entry.demand_GW = entry.proportional_demand * demand_gw
    })

    return demand_gw
}


const last_updated_at =
{
    datetime_index1: null as number | null,
    real_time: 0,
}
const max_update_frequency_ms = 1000
export function init_model_power_generated_updates(h3r5_land_cells: LandH3Cell[])
{
    const demand_GW_by_h3r4 = get_initial_proportional_demand_by_h3r4_cell(h3r5_land_cells)

    const unsub = pub_sub.sub("simulation_datetime", async (payload) =>
    {
        const current_time = performance.now()
        const current_speed_factor = get_speed_factor(hacky_get_state()?.game_datetime.speed || DEFAULT_SPEED)
        if (last_updated_at.datetime_index1 === payload.datetime_annual_hourly_index1 && current_time - last_updated_at.real_time < (max_update_frequency_ms * current_speed_factor))
        {
            // Don't update more than max_update_frequency_ms for the same datetime index
            return
        }
        last_updated_at.datetime_index1 = payload.datetime_annual_hourly_index1
        last_updated_at.real_time = current_time

        const model_state = await calculate_model_state_at_timepoint({
            demand_GW_by_h3r4,
            datetime_annual_hourly_index1: payload.datetime_annual_hourly_index1,
            datetime_annual_hourly_index2: payload.datetime_annual_hourly_index2,
            datetime_annual_hourly_index_mix: payload.datetime_annual_hourly_index_mix,
        })

        pub_sub.pub("power_gen_cap_store_and_demand", {
            ...model_state,
            demand_GW_by_h3r4,
            datetime_ms: payload.datetime_ms,
        })
    })

    return unsub
}


type CalculateModelStateAtTimepoint = {
    demand_GW_by_h3r4: Record<string, DemandGWForH3R4>
    datetime_annual_hourly_index1: number
} & ({
    datetime_annual_hourly_index2: number
    datetime_annual_hourly_index_mix: number
} | {
    datetime_annual_hourly_index2?: undefined
    datetime_annual_hourly_index_mix?: undefined
})
export async function calculate_model_state_at_timepoint(args: CalculateModelStateAtTimepoint)
{
    const {
        demand_GW_by_h3r4,
        datetime_annual_hourly_index1,
    } = args

    const {
        datetime_annual_hourly_index2 = datetime_annual_hourly_index1,
        datetime_annual_hourly_index_mix = 0,
    } = args

    console.log("Updating model power supply for datetime index", datetime_annual_hourly_index1)

    const capacity_factor_data = await promise_capacity_factor_data
    const aggregated_by_h3r4 = await await_aggregated_by_h3r4()

    const gen_cap_store_MW_by_h3r4 = get_gen_cap_store_MW_by_h3r4_cell(
        capacity_factor_data,
        aggregated_by_h3r4,
        datetime_annual_hourly_index1,
        datetime_annual_hourly_index2,
        datetime_annual_hourly_index_mix,
    )
    const generated_GW_by_type: ValueByPowerType<number> = {
        wind: 0,
        solar: 0,
        gas: 0,
        nuclear: 0,
        battery: 0,
        hydro_river: 0,
        hydro_pumped_storage: 0,
    }
    const capacity_GW_by_type: ValueByPowerType<number> = {
        ...generated_GW_by_type,
    }
    const stored_GWh_by_type: ValueByStorageType<number> = {
        battery: 0,
        hydro_pumped_storage: 0,
    }
    const store_capacity_by_type: ValueByStorageType<number> = {
        ...stored_GWh_by_type,
    }

    let total_MW = 0
    Object.values(gen_cap_store_MW_by_h3r4).forEach(c =>
    {
        total_MW += c.total_generated_MW
        generated_GW_by_type.wind += c.wind.generated_MW / 1000
        generated_GW_by_type.solar += c.solar.generated_MW / 1000
        generated_GW_by_type.gas += c.gas.generated_MW / 1000
        generated_GW_by_type.nuclear += c.nuclear.generated_MW / 1000
        generated_GW_by_type.hydro_river += c.hydro_river.generated_MW / 1000
        generated_GW_by_type.battery += c.battery.generated_MW / 1000
        generated_GW_by_type.hydro_pumped_storage += c.hydro_pumped_storage.generated_MW / 1000

        capacity_GW_by_type.wind += c.wind.capacity_MW / 1000
        capacity_GW_by_type.solar += c.solar.capacity_MW / 1000
        capacity_GW_by_type.gas += c.gas.capacity_MW / 1000
        capacity_GW_by_type.nuclear += c.nuclear.capacity_MW / 1000
        capacity_GW_by_type.hydro_river += c.hydro_river.capacity_MW / 1000
        capacity_GW_by_type.battery += c.battery.capacity_MW / 1000
        capacity_GW_by_type.hydro_pumped_storage += c.hydro_pumped_storage.capacity_MW / 1000

        stored_GWh_by_type.battery += (c.battery.stored_MWh ?? 0) / 1000
        stored_GWh_by_type.hydro_pumped_storage += (c.hydro_pumped_storage.stored_MWh ?? 0) / 1000

        store_capacity_by_type.battery += (c.battery.store_capacity_MWh ?? 0) / 1000
        store_capacity_by_type.hydro_pumped_storage += (c.hydro_pumped_storage.store_capacity_MWh ?? 0) / 1000
    })

    const generated_GW = total_MW / 1000

    const demand_GW = mutate_demand_by_h3_cell(
        capacity_factor_data.wind.date_time_to_index.size,
        demand_GW_by_h3r4,
        datetime_annual_hourly_index1,
        datetime_annual_hourly_index2,
        datetime_annual_hourly_index_mix
    )

    return {
        generated_GW,
        demand_GW,
        generated_GW_by_type,
        capacity_GW_by_type,
        stored_GWh_by_type,
        store_capacity_by_type,
        gen_cap_store_MW_by_h3r4,
    }
}


interface ModelStateAtTimepoint
{
    timestamp_ms: number
    timestamp_index: number
    demand_GW: number
    generated_GW_by_type: ValueByPowerType<number>
    capacity_GW_by_type: ValueByPowerType<number>
    stored_GWh_by_type: ValueByStorageType<number>
    store_capacity_by_type: ValueByStorageType<number>
}
export async function calculate_model_state_over_time_range(args: {
    demand_GW_by_h3r4: Record<string, DemandGWForH3R4>
    start_timestamp: number
    end_timestamp: number
}): Promise<ModelStateAtTimepoint[]>
{
    let index = timestamp_to_index(args.start_timestamp)
    const end_index = timestamp_to_index(args.end_timestamp)

    const model_states: ModelStateAtTimepoint[] = []
    while (index <= end_index)
    {
        const timestamp_ms = args.start_timestamp + index * 1000 * 3600
        const model_state = await calculate_model_state_at_timepoint({
            demand_GW_by_h3r4: args.demand_GW_by_h3r4,
            datetime_annual_hourly_index1: index,
            datetime_annual_hourly_index2: index, // not rele
            datetime_annual_hourly_index_mix: 0,
        })

        model_states.push(deep_freeze({
            timestamp_ms: timestamp_ms,
            timestamp_index: index,
            demand_GW: model_state.demand_GW,
            generated_GW_by_type: model_state.generated_GW_by_type,
            capacity_GW_by_type: model_state.capacity_GW_by_type,
            stored_GWh_by_type: model_state.stored_GWh_by_type,
            store_capacity_by_type: model_state.store_capacity_by_type,
        }))

        ++index
    }

    return model_states
}
